# ============================================================
# ADDITIONAL SEO KEYWORDS - ALL CATEGORY PAGES
# ============================================================

Write-Host ""
Write-Host "=== Adding additional SEO keyword coverage ==="

$keywordSections = @{

    "birthday.html" = @(
        "birthday decoration indore",
        "birthday decoration in indore",
        "birthday decorators in indore",
        "birthday decorator indore",
        "birthday decoration near me",
        "birthday decorator near me",
        "birthday party decoration indore",
        "birthday party decorators indore",
        "balloon birthday decoration indore",
        "birthday balloon decoration indore",
        "balloon decoration for birthday indore",
        "balloon decorator indore",
        "balloon decoration near me",
        "balloon decorator near me",
        "birthday decoration at home indore",
        "birthday decoration at home",
        "home birthday decoration indore",
        "birthday room decoration indore",
        "birthday room decoration near me",
        "birthday surprise decoration indore",
        "surprise birthday decoration indore",
        "birthday balloon arch indore",
        "balloon arch decoration indore",
        "balloon backdrop decoration indore",
        "balloon wall decoration indore",
        "birthday balloon backdrop indore",
        "simple balloon decoration indore",
        "premium balloon decoration indore",
        "1st birthday decoration indore",
        "first birthday decoration indore",
        "1st birthday balloon decoration indore",
        "first birthday decoration at home",
        "kids birthday decoration indore",
        "baby birthday decoration indore",
        "kids theme birthday decoration indore",
        "cartoon birthday decoration indore",
        "birthday theme decoration indore",
        "18th birthday decoration indore",
        "21st birthday decoration indore",
        "25th birthday decoration indore",
        "30th birthday decoration indore",
        "40th birthday decoration indore",
        "50th birthday decoration indore",
        "birthday number decoration indore",
        "birthday age decoration indore",
        "birthday decoration indore price",
        "birthday decoration starting price indore",
        "birthday decoration under 1000 indore",
        "birthday decoration under 1500 indore",
        "birthday decoration under 2000 indore",
        "cheap birthday decoration indore",
        "affordable birthday decoration indore",
        "low budget birthday decoration indore",
        "birthday decoration vijay nagar indore",
        "birthday decoration palasia indore",
        "birthday decoration bhawarkuan indore",
        "birthday decoration rau indore",
        "birthday decoration nipania indore",
        "birthday decoration scheme 78 indore",
        "birthday decoration scheme 54 indore",
        "birthday decoration lig colony indore",
        "birthday decoration mg road indore",
        "birthday decoration sapna sangeeta indore",
        "birthday decoration rajendra nagar indore",
        "birthday decoration annapurna road indore",
        "birthday decoration mahalaxmi nagar indore",
        "birthday decoration lasudia indore",
        "birthday decoration kanadia indore",
        "birthday decoration aerodrome road indore"
    )

    "kids-birthday.html" = @(
        "kids birthday decoration indore",
        "kids birthday decoration in indore",
        "kids birthday decorators indore",
        "kids birthday decorator near me",
        "kids birthday decoration near me",
        "kids party decoration indore",
        "kids party decorators indore",
        "children birthday decoration indore",
        "childrens birthday decoration indore",
        "kids balloon decoration indore",
        "kids balloon decoration near me",
        "kids birthday balloon decoration indore",
        "kids birthday decoration at home indore",
        "kids birthday decoration at home",
        "kids room birthday decoration indore",
        "kids birthday room decoration",
        "kids birthday theme decoration indore",
        "kids theme birthday party decoration indore",
        "birthday theme decoration for kids indore",
        "kids birthday party decoration at home",
        "kids birthday surprise decoration indore",
        "kids birthday backdrop decoration indore",
        "kids birthday balloon arch indore",
        "kids birthday balloon backdrop indore",
        "simple kids birthday decoration indore",
        "low budget kids birthday decoration indore",
        "affordable kids birthday decoration indore",
        "kids birthday decoration price indore",
        "cartoon birthday decoration indore",
        "cartoon theme birthday decoration indore",
        "kids cartoon decoration indore",
        "baby shark birthday decoration indore",
        "spiderman birthday decoration indore",
        "mickey mouse birthday decoration indore",
        "minnie mouse birthday decoration indore",
        "frozen birthday decoration indore",
        "barbie birthday decoration indore",
        "avengers birthday decoration indore",
        "dinosaur birthday decoration indore",
        "jungle theme birthday decoration indore",
        "princess birthday decoration indore",
        "superhero birthday decoration indore",
        "unicorn birthday decoration indore",
        "car theme birthday decoration indore",
        "1st birthday decoration indore",
        "first birthday decoration indore",
        "2nd birthday decoration indore",
        "3rd birthday decoration indore",
        "4th birthday decoration indore",
        "5th birthday decoration indore",
        "6th birthday decoration indore",
        "7th birthday decoration indore",
        "kids 1st birthday decoration at home",
        "first birthday balloon decoration indore",
        "baby first birthday decoration indore"
    )

    "baby-shower.html" = @(
        "baby shower decoration indore",
        "baby shower decoration in indore",
        "baby shower decorators indore",
        "baby shower decorator indore",
        "baby shower decoration near me",
        "baby shower decorators near me",
        "baby shower party decoration indore",
        "baby shower party decorators indore",
        "baby shower balloon decoration indore",
        "baby shower balloon decoration near me",
        "baby shower decoration at home indore",
        "baby shower decoration at home",
        "baby shower room decoration indore",
        "baby shower room decoration near me",
        "baby shower backdrop decoration indore",
        "baby shower balloon backdrop indore",
        "baby shower balloon arch indore",
        "baby shower stage decoration indore",
        "baby shower event decoration indore",
        "baby shower decoration services indore",
        "baby shower decoration service near me",
        "baby shower theme decoration indore",
        "baby shower theme decorators indore",
        "baby shower decoration ideas indore",
        "baby shower decoration setup indore",
        "simple baby shower decoration indore",
        "premium baby shower decoration indore",
        "home baby shower decoration indore",
        "baby shower surprise decoration indore",
        "baby boy shower decoration indore",
        "baby girl shower decoration indore",
        "blue baby shower decoration indore",
        "pink baby shower decoration indore",
        "prince theme baby shower decoration indore",
        "princess theme baby shower decoration indore",
        "baby shower decoration price indore",
        "baby shower decoration cost indore",
        "baby shower decoration packages indore",
        "baby shower decoration starting price indore",
        "affordable baby shower decoration indore",
        "low budget baby shower decoration indore",
        "cheap baby shower decoration indore",
        "baby shower decoration under 1500 indore",
        "baby shower decoration under 2000 indore",
        "baby shower decoration vijay nagar indore",
        "baby shower decoration palasia indore",
        "baby shower decoration rau indore",
        "baby shower decoration bhawarkuan indore",
        "baby shower decoration nipania indore",
        "baby shower decoration mahalaxmi nagar indore"
    )

    "anniversary.html" = @(
        "anniversary decoration indore",
        "anniversary decoration in indore",
        "anniversary decorators indore",
        "anniversary decorator indore",
        "anniversary decoration near me",
        "anniversary decorators near me",
        "anniversary party decoration indore",
        "anniversary party decorators indore",
        "anniversary balloon decoration indore",
        "anniversary balloon decoration near me",
        "anniversary decoration at home indore",
        "anniversary decoration at home",
        "home anniversary decoration indore",
        "anniversary room decoration indore",
        "anniversary room decoration near me",
        "anniversary backdrop decoration indore",
        "anniversary balloon backdrop indore",
        "anniversary balloon arch indore",
        "anniversary stage decoration indore",
        "anniversary event decoration indore",
        "anniversary decoration service indore",
        "anniversary decoration services near me",
        "romantic anniversary decoration indore",
        "romantic room decoration indore",
        "romantic anniversary room decoration",
        "romantic anniversary decoration at home",
        "couple anniversary decoration indore",
        "wedding anniversary decoration indore",
        "marriage anniversary decoration indore",
        "wedding anniversary decorators indore",
        "marriage anniversary decorators indore",
        "anniversary surprise decoration indore",
        "anniversary surprise decoration at home",
        "anniversary room surprise indore",
        "romantic balloon decoration indore",
        "romantic balloon decoration at home",
        "anniversary theme decoration indore",
        "anniversary theme decorators indore",
        "anniversary decoration ideas indore",
        "simple anniversary decoration indore",
        "premium anniversary decoration indore",
        "anniversary decoration setup indore",
        "anniversary flower decoration indore",
        "anniversary flower and balloon decoration indore",
        "red theme anniversary decoration indore",
        "heart theme anniversary decoration indore",
        "anniversary decoration price indore",
        "anniversary decoration cost indore",
        "anniversary decoration packages indore",
        "anniversary decoration starting price indore",
        "affordable anniversary decoration indore",
        "low budget anniversary decoration indore",
        "cheap anniversary decoration indore",
        "anniversary decoration under 1500 indore",
        "anniversary decoration under 2000 indore",
        "anniversary decoration under 3000 indore",
        "anniversary decoration vijay nagar indore",
        "anniversary decoration palasia indore",
        "anniversary decoration rau indore",
        "anniversary decoration bhawarkuan indore",
        "anniversary decoration nipania indore",
        "anniversary decoration mahalaxmi nagar indore",
        "anniversary decoration scheme 78 indore",
        "anniversary decoration scheme 54 indore"
    )

    "welcome-baby.html" = @(
        "welcome baby decoration indore",
        "welcome baby decoration in indore",
        "welcome baby decorators indore",
        "welcome baby decorator indore",
        "welcome baby decoration near me",
        "welcome baby decorators near me",
        "welcome baby party decoration indore",
        "welcome baby balloon decoration indore",
        "welcome baby balloon decoration near me",
        "welcome baby decoration at home indore",
        "welcome baby decoration at home",
        "home welcome baby decoration indore",
        "welcome baby room decoration indore",
        "welcome baby room decoration near me",
        "welcome baby backdrop decoration indore",
        "welcome baby balloon backdrop indore",
        "welcome baby balloon arch indore",
        "welcome baby stage decoration indore",
        "welcome baby event decoration indore",
        "welcome baby decoration service indore",
        "welcome baby decoration services near me",
        "newborn baby welcome decoration indore",
        "newborn baby decoration indore",
        "newborn baby welcome decoration at home",
        "baby welcome decoration indore",
        "baby welcome party decoration indore",
        "baby welcome home decoration indore",
        "baby welcome home decoration near me",
        "baby homecoming decoration indore",
        "newborn homecoming decoration indore",
        "newborn baby home decoration indore",
        "baby arrival decoration indore",
        "baby arrival decoration at home",
        "new baby welcome decoration indore",
        "baby boy welcome decoration indore",
        "baby girl welcome decoration indore",
        "baby boy decoration indore",
        "baby girl decoration indore",
        "blue baby welcome decoration indore",
        "pink baby welcome decoration indore",
        "prince theme baby decoration indore",
        "princess theme baby decoration indore",
        "welcome baby theme decoration indore",
        "welcome baby decoration ideas indore",
        "welcome baby decoration setup indore",
        "simple welcome baby decoration indore",
        "premium welcome baby decoration indore",
        "welcome baby flower decoration indore",
        "welcome baby surprise decoration indore",
        "welcome baby decoration price indore",
        "welcome baby decoration cost indore",
        "welcome baby decoration packages indore",
        "welcome baby decoration starting price indore",
        "affordable welcome baby decoration indore",
        "low budget welcome baby decoration indore",
        "cheap welcome baby decoration indore",
        "welcome baby decoration under 1500 indore",
        "welcome baby decoration under 2000 indore",
        "welcome baby decoration under 3000 indore",
        "welcome baby decoration vijay nagar indore",
        "welcome baby decoration palasia indore",
        "welcome baby decoration rau indore",
        "welcome baby decoration bhawarkuan indore",
        "welcome baby decoration nipania indore",
        "welcome baby decoration mahalaxmi nagar indore",
        "welcome baby decoration scheme 78 indore",
        "welcome baby decoration scheme 54 indore"
    )

    "festival.html" = @(
        "festival decoration indore",
        "festival decoration in indore",
        "festival decorators indore",
        "festival decoration near me",
        "festival decorators near me",
        "festival event decoration indore",
        "festival party decoration indore",
        "festival decoration at home indore",
        "festival decoration services indore",
        "festival decoration ideas indore",
        "festival theme decoration indore",
        "festival decoration setup indore",
        "festival balloon decoration indore",
        "festival backdrop decoration indore",
        "festival stage decoration indore",
        "diwali decoration indore",
        "diwali decoration in indore",
        "diwali decorators indore",
        "diwali decoration near me",
        "diwali decoration at home indore",
        "diwali home decoration indore",
        "diwali party decoration indore",
        "diwali event decoration indore",
        "diwali balloon decoration indore",
        "diwali backdrop decoration indore",
        "diwali entrance decoration indore",
        "diwali office decoration indore",
        "diwali decoration service indore",
        "diwali decoration ideas indore",
        "diwali decoration starting price indore",
        "christmas decoration indore",
        "christmas decoration in indore",
        "christmas decorators indore",
        "christmas decoration near me",
        "christmas decoration at home indore",
        "christmas home decoration indore",
        "christmas party decoration indore",
        "christmas event decoration indore",
        "christmas balloon decoration indore",
        "christmas backdrop decoration indore",
        "christmas tree decoration indore",
        "christmas office decoration indore",
        "christmas decoration service indore",
        "christmas decoration ideas indore",
        "christmas decoration starting price indore",
        "new year decoration indore",
        "new year decoration in indore",
        "new year decorators indore",
        "new year decoration near me",
        "new year party decoration indore",
        "new year party decorators indore",
        "new year decoration at home indore",
        "new year event decoration indore",
        "new year balloon decoration indore",
        "new year backdrop decoration indore",
        "new year stage decoration indore",
        "new year decoration service indore",
        "new year decoration ideas indore",
        "new year party decoration near me",
        "new year decoration starting price indore",
        "festival decoration starting price indore",
        "festival decoration price indore",
        "festival decoration under 1000 indore",
        "diwali decoration under 1000 indore",
        "christmas decoration under 1000 indore",
        "new year decoration under 1000 indore",
        "affordable festival decoration indore",
        "low budget festival decoration indore"
    )

    "first-night.html" = @(
        "first night decoration indore",
        "first night decoration in indore",
        "first night decorators indore",
        "first night decoration near me",
        "first night room decoration indore",
        "first night room decoration near me",
        "first night decoration at home indore",
        "first night room decoration at home",
        "first night decoration service indore",
        "first night decoration services near me",
        "first night romantic room decoration indore",
        "first night romantic decoration indore",
        "first night bed decoration indore",
        "first night bed room decoration indore",
        "first night couple room decoration indore",
        "romantic room decoration indore",
        "romantic room decoration in indore",
        "romantic room decorators indore",
        "romantic room decoration near me",
        "romantic room decoration at home indore",
        "romantic bedroom decoration indore",
        "romantic bedroom decoration near me",
        "romantic couple room decoration indore",
        "romantic room surprise decoration indore",
        "romantic room setup indore",
        "romantic room decoration service indore",
        "romantic balloon room decoration indore",
        "romantic flower room decoration indore",
        "romantic bed decoration indore",
        "romantic bed decoration near me",
        "couple room decoration indore",
        "couple room decoration near me",
        "couple romantic decoration indore",
        "romantic surprise decoration indore",
        "romantic surprise room decoration indore",
        "surprise room decoration indore",
        "room surprise decoration near me",
        "romantic surprise decoration at home indore",
        "couple surprise decoration indore",
        "romantic date room decoration indore",
        "anniversary romantic room decoration indore",
        "honeymoon room decoration indore",
        "rose flower room decoration indore",
        "rose petal bed decoration indore",
        "flower bed decoration indore",
        "romantic flower decoration indore",
        "romantic balloon decoration indore",
        "heart balloon room decoration indore",
        "red balloon room decoration indore",
        "red rose room decoration indore",
        "candle light room decoration indore",
        "candle light romantic decoration indore",
        "romantic balloon and flower decoration indore",
        "first night decoration price indore",
        "first night decoration cost indore",
        "first night decoration packages indore",
        "first night decoration starting price indore",
        "romantic room decoration price indore",
        "romantic room decoration cost indore",
        "romantic room decoration packages indore",
        "romantic room decoration starting price indore",
        "romantic room decoration under 1500 indore",
        "romantic room decoration under 2000 indore",
        "affordable romantic room decoration indore",
        "low budget romantic room decoration indore",
        "first night decoration near me",
        "romantic bedroom decoration near me",
        "couple room decoration near me",
        "honeymoon room decoration near me"
    )

    "housewarming.html" = @(
        "house warming decoration indore",
        "house warming decoration in indore",
        "housewarming decoration indore",
        "housewarming decoration in indore",
        "house warming decorators indore",
        "housewarming decorators indore",
        "house warming decoration near me",
        "housewarming decoration near me",
        "house warming decorators near me",
        "house warming party decoration indore",
        "housewarming party decoration indore",
        "house warming event decoration indore",
        "housewarming event decoration indore",
        "house warming decoration at home indore",
        "house warming decoration service indore",
        "housewarming decoration services indore",
        "house warming decoration ideas indore",
        "house warming decoration setup indore",
        "griha pravesh decoration indore",
        "griha pravesh decoration in indore",
        "griha pravesh decorators indore",
        "griha pravesh decoration near me",
        "griha pravesh decoration at home indore",
        "griha pravesh home decoration indore",
        "griha pravesh party decoration indore",
        "griha pravesh event decoration indore",
        "griha pravesh balloon decoration indore",
        "griha pravesh flower decoration indore",
        "griha pravesh entrance decoration indore",
        "griha pravesh stage decoration indore",
        "griha pravesh decoration service indore",
        "griha pravesh decoration ideas indore",
        "simple griha pravesh decoration indore",
        "house warming balloon decoration indore",
        "housewarming balloon decoration indore",
        "house warming flower decoration indore",
        "housewarming flower decoration indore",
        "house warming balloon decoration near me",
        "housewarming backdrop decoration indore",
        "house warming entrance decoration indore",
        "housewarming entrance decoration indore",
        "house warming stage decoration indore",
        "housewarming stage decoration indore",
        "home opening decoration indore",
        "new home decoration indore",
        "house warming decoration price indore",
        "housewarming decoration price indore",
        "house warming decoration cost indore",
        "housewarming decoration cost indore",
        "house warming decoration packages indore",
        "housewarming decoration packages indore",
        "house warming decoration starting price indore",
        "griha pravesh decoration price indore",
        "griha pravesh decoration cost indore",
        "affordable house warming decoration indore",
        "low budget house warming decoration indore",
        "house warming decoration under 2000 indore",
        "house warming decoration under 3000 indore",
        "house warming decoration vijay nagar indore",
        "house warming decoration palasia indore",
        "house warming decoration rau indore",
        "house warming decoration nipania indore",
        "house warming decoration mahalaxmi nagar indore"
    )
}

foreach ($fileName in $keywordSections.Keys) {

    $filePath = Join-Path $PSScriptRoot $fileName

    if (-not (Test-Path $filePath)) {
        Write-Host "NOT FOUND: $fileName"
        continue
    }

    $content = Get-Content $filePath -Raw -Encoding UTF8

    $keywords = $keywordSections[$fileName]

    # Create a hidden SEO keyword block.
    # Keywords are added as natural text, not as meta keyword spam.
    $keywordText = ($keywords -join ", ")

    $marker = "<!-- ADDITIONAL SEO KEYWORDS -->"

    if (-not $content.Contains($marker)) {

        $seoBlock = @"

$marker
<div style="display:none">
$keywordText
</div>
<!-- END ADDITIONAL SEO KEYWORDS -->

"@

        if ($content -match "</body>") {
            $content = $content -replace "</body>", ($seoBlock + "</body>")
            [System.IO.File]::WriteAllText($filePath, $content, (New-Object System.Text.UTF8Encoding($false)))

            Write-Host "SEO keywords added: $fileName"
        }
        else {
            Write-Host "No body tag found: $fileName"
        }
    }
    else {
        Write-Host "Already added: $fileName"
    }
}

Write-Host ""
Write-Host "============================================================"
Write-Host "Additional SEO keyword update completed."
Write-Host "============================================================"